# Generated by Django 6.0.3 on 2026-04-01 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartRecommendation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar Chart'), ('line', 'Line Chart'), ('scatter', 'Scatter Plot'), ('histogram', 'Histogram'), ('heatmap', 'Correlation Heatmap'), ('box', 'Box Plot'), ('treemap', 'Treemap'), ('pie', 'Pie Chart'), ('area', 'Area Chart')], max_length=30)),
                ('x_column', models.CharField(blank=True, max_length=200)),
                ('y_column', models.CharField(blank=True, max_length=200)),
                ('color_column', models.CharField(blank=True, max_length=200)),
                ('reasoning', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(default=1)),
                ('plotly_config', models.JSONField(default=dict)),
                ('generated_by', models.CharField(choices=[('rules', 'Rule Engine'), ('ai', 'AI Model')], default='rules', max_length=20)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_recommendations', to='datasets.dataset')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedChart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('plotly_config', models.JSONField(default=dict)),
                ('custom_config', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_charts', to='datasets.dataset')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizations.chartrecommendation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardChart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=6)),
                ('height', models.IntegerField(default=4)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizations.dashboard')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizations.savedchart')),
            ],
            options={
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='charts',
            field=models.ManyToManyField(through='visualizations.DashboardChart', to='visualizations.savedchart'),
        ),
    ]
