# Generated by Django 6.0.3 on 2026-04-01 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('isolation_forest', 'Isolation Forest (multivariate)'), ('zscore', 'Z-Score (univariate)'), ('iqr', 'Interquartile Range')], max_length=30)),
                ('contamination_rate', models.FloatField(default=0.05)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('anomaly_indices', models.JSONField(default=list)),
                ('feature_importance', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_reports', to='datasets.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CorrelationMatrix',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(default='pearson', max_length=20)),
                ('matrix_data', models.JSONField(default=dict)),
                ('strong_correlations', models.JSONField(default=list)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_matrix', to='datasets.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_by_task', models.CharField(blank=True, max_length=200)),
                ('profile_data', models.JSONField(default=dict)),
                ('key_insights', models.JSONField(default=list)),
                ('ai_narrative', models.TextField(blank=True)),
                ('ai_narrative_generated_at', models.DateTimeField(blank=True, null=True)),
                ('completeness_score', models.FloatField(null=True)),
                ('consistency_score', models.FloatField(null=True)),
                ('uniqueness_score', models.FloatField(null=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='datasets.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NLQueryResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('generated_sql', models.TextField(blank=True)),
                ('sql_explanation', models.TextField(blank=True)),
                ('result_data', models.JSONField(default=list)),
                ('result_row_count', models.IntegerField(default=0)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('execution_error', models.TextField(blank=True)),
                ('chart_config', models.JSONField(default=dict)),
                ('llm_provider', models.CharField(blank=True, max_length=50)),
                ('llm_model', models.CharField(blank=True, max_length=100)),
                ('llm_tokens_used', models.IntegerField(default=0)),
                ('was_successful', models.BooleanField(default=False)),
                ('asked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nl_queries', to='datasets.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
