# Generated by Django 6.0.3 on 2026-04-01 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('pdf', 'PDF Report'), ('excel', 'Excel Workbook')], max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('include_profile', models.BooleanField(default=True)),
                ('include_charts', models.BooleanField(default=True)),
                ('include_anomalies', models.BooleanField(default=True)),
                ('include_nl_queries', models.BooleanField(default=False)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('generation_time_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=200)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='datasets.dataset')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
